### ISSUE TITLE
[BUG] [SSH Logs] Parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value.

### ISSUE THREAD

**Issue by perrfect** [voidquark/grafana-dashboards#6] opened 2024-04-09 18:44 UTC
**Loki Version:** [2.9.6]
**Grafana Version:** [10.4.1]
**Promtail Version:** [2.9.6]
**Dashboard Name:** [SSH Logs]

Hello. I'm using your SSH Logs dashboard and all the time getting the error:
```
Error
parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~".*" does not meet this requirement, but app=~".+" will
```

In my case promtail.conf looks like:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: messages
      __path__: /var/log/messages
- job_name: audit
  static_configs:
  - targets:
      - localhost
    labels:
      job: audit
      __path__: /var/log/audit/*.log
- job_name: secure
  static_configs:
  - targets:
      - localhost
    labels:
      job: secure
      __path__: /var/log/secure
```
And in a grafana I chose all **Label name**, all **Label Value** and all **Job**
![1](https://github.com/voidquark/grafana-dashboards/assets/39082702/dc21aed1-f02d-46c3-8f00-16f716830195)

Could you please help me solve the problem?

**Comment by voidquark** [comment] 2024-04-09 19:17
Please ensure that you select the correct labels and that the dashboard is targeting one host at a time. In your case, please make sure to select:

- `label_value` as your target host
- `secure` as the job

Once you've selected the above labels, you should see data in the dashboard. Could you please confirm this? Ensure that your timeframe is correct and that the logs exist for the selected time period.

FYI:
The error message you're encountering is related to the issue discussed here: https://github.com/grafana/loki/issues/7816. I won't consider this as a bug.

**Comment by perrfect** [comment] 2024-04-10 19:25
@voidquark Hello. Thank you for your reply.
The dashboard shows data, but when I want to change the timeframe I'm getting the error.
Main idea is that I want to see all ssh logs for all hosts. It is very important for me.

**Comment by voidquark** [comment] 2024-04-11 08:44
I'll likely need to release a new revision to prevent selecting multiple hosts. The dashboard functions properly with only one host. Could you please rerun with just one host?

Thanks for the feedback. I'll consider creating another dashboard for an overview of all hosts, but that would require building a separate one (a multi-host SSH dashboard).

**Comment by perrfect** [comment] 2024-04-11 18:50
@voidquark Hello. Yes, with one host in one period of time works correctly.
Let me know when I can try multi-host SSH dashboard.
Thank you so much.

**Comment by voidquark** [comment] 2024-04-12 21:49
Thank you for confirming. If you'd like to stay informed about its release, you have a few options:

- Click on the 'watch' button at the top of this repository.
- Subscribe to [RSS feed](https://voidquark.com/blog/rss.xml) or [Atom feed](https://voidquark.com/blog/atom.xml).
- Sign up for our newsletter or follow us on social media.

I'll go ahead and close this issue since it's not a bug.

**Closed as completed by voidquark** 2024-04-12 21:49 UTC
Labels: bug
